version: '3'
services:
  mariadb:
    image: cgr.dev/chainguard/mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 7gtrgdgt5j
      MARIADB_DATABASE: dreamfactory
    volumes:
      - df-mysql:/var/lib/mysql
        
      
  redis:
    image: cgr.dev/chainguard/redis:latest
    container_name: redis

  web:
    environment:
      SERVERNAME: dreamfactory.local
#      HTTPS_HEADER: "on"
      # APP_KEY: VALUE
      DB_DRIVER: mysql
      DB_HOST: mariadb
      DB_USERNAME: root
      DB_PASSWORD: 7gtrgdgt5j
      DB_DATABASE: dreamfactory
      DB_CHARSET: utf8
      DB_COLLATION: utf8_general_ci
      CACHE_DRIVER: redis
      CACHE_HOST: redis
      CACHE_DATABASE: 0
      CACHE_PORT: 6379

#      APP_LOG_LEVEL: debug
#      LOG_TO_STDOUT: "true"
#      APP_DEBUG: "true"

#      Uncomment and configure to enable emailing
#      SENDMAIL_DEFAULT_COMMAND: "/usr/sbin/sendmail -t"
#      SSMTP_root:
#      SSMTP_mailhub:
#      SSMTP_AuthUser:
#      SSMTP_AuthPass:
#      SSMTP_UseSTARTTLS:
#      SSMTP_UseTLS:
#      SSMTP_AuthMethod:
#      SSMTP_FromLineOverride:

#      Uncomment to enable Logs DB
#      LOGSDB_HOST: logsdb
#      LOGSDB_DATABASE: access_log
#      LOGSDB_USERNAME: mongoadmin
#      LOGSDB_PASSWORD: password
#      LOGSDB_ENABLED: "true"
    volumes:
      - df-storage:/opt/dreamfactory/storage
    build: .
    ports:
      - "80:80"

#  Uncomment to enable Logs DB
#  logsdb:
#    image: mongo:4.0-xenial
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongoadmin
#      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  df-storage:
    driver: local
  df-mysql:
    driver: local
